# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSessionExport < Formula
  desc "Transform Claude Code sessions into shareable HTML documentation"
  homepage "https://github.com/robzolkos/claude-session-export"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v1.0.0/claude-session-export_1.0.0_darwin_amd64.tar.gz"
      sha256 "5f2484bbd3b8d4fc510d5ca58164d01a337a35686649744c739ba09fb2641b98"

      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v1.0.0/claude-session-export_1.0.0_darwin_arm64.tar.gz"
      sha256 "a3a3050fc5440f296373df04188fa4a5927e82b3108632350b4f962c3615af4f"

      def install
        bin.install "claude-session-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v1.0.0/claude-session-export_1.0.0_linux_amd64.tar.gz"
      sha256 "474298f1c5131d0cea0a675e607bb04e1d67fba602015f953885a8278621a182"
      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v1.0.0/claude-session-export_1.0.0_linux_arm64.tar.gz"
      sha256 "57de9d3db880f2ca5eb5cf08145610001d0350c0f260c957fdfa2918924b2f7f"
      def install
        bin.install "claude-session-export"
      end
    end
  end
end
