# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSessionExport < Formula
  desc "Transform Claude Code sessions into shareable HTML documentation"
  homepage "https://github.com/robzolkos/claude-session-export"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.9.0/claude-session-export_0.9.0_darwin_amd64.tar.gz"
      sha256 "aaa2baa3cbd8c885b21a5667a61153f4b14a60a06fa477f5689c117955714a04"

      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.9.0/claude-session-export_0.9.0_darwin_arm64.tar.gz"
      sha256 "90d636b06c390ad0fe8b743335856ca96dcf1b0d542e249a1df2637a5f40fedc"

      def install
        bin.install "claude-session-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.9.0/claude-session-export_0.9.0_linux_amd64.tar.gz"
      sha256 "51ea301153fcc99d8a8414606de05b53cc1d4c255a078b62d5645f395b641e5e"
      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.9.0/claude-session-export_0.9.0_linux_arm64.tar.gz"
      sha256 "782af40d4a763043905f40a8b9a2c340587e5d3a750432ea18780f0c4f10290e"
      def install
        bin.install "claude-session-export"
      end
    end
  end
end
