# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSessionExport < Formula
  desc "Transform Claude Code sessions into shareable HTML documentation"
  homepage "https://github.com/robzolkos/claude-session-export"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.8.1/claude-session-export_0.8.1_darwin_amd64.tar.gz"
      sha256 "93bda6a2963e98f5d285d9f3b79fb44fe07940445f06a15bf0bc0357d3934340"

      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.8.1/claude-session-export_0.8.1_darwin_arm64.tar.gz"
      sha256 "11052109fcd174dfd0b8def8e0c7fef9e7b8858be4d9fe7265ea62c787fc7244"

      def install
        bin.install "claude-session-export"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.8.1/claude-session-export_0.8.1_linux_amd64.tar.gz"
      sha256 "ef8cdc6b442c5c8c03c88aaa1411cc7f58f9557b14c116c73ba02035ca35ca3a"
      def install
        bin.install "claude-session-export"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robzolkos/claude-session-export/releases/download/v0.8.1/claude-session-export_0.8.1_linux_arm64.tar.gz"
      sha256 "5c106a8a20e332f8d328fc98dfa6a6527e185786eaf4b5da9ca31e22226299a0"
      def install
        bin.install "claude-session-export"
      end
    end
  end
end
